# Generated by Django 3.1.2 on 2020-10-15 02:51

import businesscardocr.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCardOcr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=businesscardocr.models.user_path, verbose_name='이미지')),
                ('type', models.CharField(choices=[('Recognizing', '인식중'), ('Unrecognizable', '인식불가'), ('Success', '인식성공')], default='0', help_text='인식 유형', max_length=50, verbose_name='인식 유형')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesscardocr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '명함 인식',
                'verbose_name_plural': '명함 인식 목록',
                'ordering': ['-create_date'],
            },
        ),
    ]
