# Generated by Django 3.1.2 on 2020-10-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Notice/%Y/%m/%d', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
