# Generated by Django 3.1.2 on 2020-10-15 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupbusinesscard', '0002_auto_20201015_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCardBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesscardbook', to='groupbusinesscard.groupbusinesscard')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesscardbook', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '명함첩',
                'verbose_name_plural': '명함첩 목록',
                'ordering': ['-create_date'],
            },
        ),
    ]
